[package]
name = "when-rs"
version = "0.1.0"
authors = ["Aleksandar Janicijevic <ajanicij@vogonsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1"
chrono = "0.4"
atty = "0.2"
